[tool.black]
line-length = 100
target-version = ["py311"]
exclude = "\.venv|build|dist"

[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E","F","I","B","UP"]
ignore = ["E501"]
exclude = ["build","dist",".venv"]
